# Generated by Django 5.0.2 on 2024-05-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_task_title_task_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
