# Generated by Django 5.0.2 on 2024-05-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_task_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_vdo', models.FileField(upload_to='detection/')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
            ],
        ),
    ]
